package com.pousheng.middle.order.impl.dao;

import com.google.common.collect.ImmutableMap;
import com.pousheng.middle.order.model.PoushengEspLog;
import io.terminus.common.mysql.dao.MyBatisDao;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: Esp快递日志Dao类
 * Date: 2019-09-10
 */
@Repository
public class PoushengEspLogDao extends MyBatisDao<PoushengEspLog> {

    public PoushengEspLog findByShipmentCode(String shipmentCode) {
        return this.sqlSession.selectOne(sqlId("findByShipmentCode"), ImmutableMap.of("middleShipmentNo", shipmentCode));
    }

    public List<PoushengEspLog> findToRetryLog(Map<String, Object> params) {
        return this.sqlSession.selectList(sqlId("findToRetryLog"), params);
    }

}
