package com.pousheng.middle.order.impl.dao;

import com.google.common.collect.ImmutableMap;
import com.pousheng.middle.order.model.PoushengConfig;
import io.terminus.common.mysql.dao.MyBatisDao;
import org.springframework.stereotype.Repository;

/**
 * Code generated by terminus code gen
 * Desc: 配置表Dao类
 * Date: 2019-06-26
 */
@Repository
public class PoushengConfigDao extends MyBatisDao<PoushengConfig> {

    public PoushengConfig findByType(String type) {
        return getSqlSession().selectOne(sqlId("findByType"), ImmutableMap.of("type", type));
    }
}
