package com.pousheng.middle.order.impl.dao;

import com.pousheng.middle.order.model.ReverseExpressInfo;
import com.pousheng.middle.order.model.ReverseHeadlessInfo;
import io.terminus.common.mysql.dao.MyBatisDao;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

/**
 * Code generated by terminus code gen Desc: Dao类 Date: 2019-06-03
 */
@Repository
public class ReverseExpressInfoDao extends MyBatisDao<ReverseExpressInfo> {

   public ReverseExpressInfo findReverseExpressInfoByExpressNo(String expressNo) {

        return super.sqlSession.selectOne("findReverseExpressInfoByExpressNo", expressNo);

    }

    public Long countReverseExpress(Map<String, Object> reverseExpressCriteria){
        return (Long)this.sqlSession.selectOne(this.sqlId("count"), reverseExpressCriteria);
    }

    public ReverseExpressInfo findExpressByTransferAndLine(Map<String, Object> reverseExpressCriteria){
        return super.sqlSession.selectOne(this.sqlId("findExpressByTransferAndLine"), reverseExpressCriteria);
    }

    public int batchCreate(List<ReverseExpressInfo> list) {
        return this.sqlSession.insert(sqlId("batchCreate"), list);
    }


}
