package com.pousheng.middle.order.impl.dao;

import com.pousheng.middle.order.dto.reverseLogistic.ReverseInstoreCriteria;
import com.pousheng.middle.order.model.ReverseInstoreInfo;
import io.terminus.common.mysql.dao.MyBatisDao;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

/**
 * Code generated by terminus code gen Desc: Dao类 Date: 2019-06-03
 */
@Repository
public class ReverseInstoreInfoDao extends MyBatisDao<ReverseInstoreInfo> {

    public ReverseInstoreInfo findReverseExpressInfoByInstoreNoAndDetailNo(ReverseInstoreCriteria query) {

        return super.sqlSession.selectOne(this.sqlId("findReverseExpressInfoByInstoreNoAndDetailNo"), query);
    }

    public Long countReverseInstore(Map<String, Object> reverseInstoreCriteria) {
        return (Long)this.sqlSession.selectOne(this.sqlId("count"), reverseInstoreCriteria);
    }
    public int batchCreate(List<ReverseInstoreInfo> list) {
        return this.sqlSession.insert(sqlId("batchCreate"), list);
    }

}
