spring:
  datasource:
    initialize: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

terminus:
  rocketmq:
    nameServerAddress: ${MQ_NAME_ADDR:127.0.0.1:9876}
    producerGroup: ${MQ_PRODUCER_GROUP:default-index-producer}

mq:
  topic: scanner
  consumeThreadMin: 2
  consumeThreadMax: 8
  name-server-addr: ${MQ_NAME_ADDR:127.0.0.1:9876}
  consume-group: default-index-consumer


# es基础配置
search:
  host: ${POUSHENG_ES_HOST:127.0.0.1}
  port: ${POUSHENG_ES_PORT:9200}

order:
  search:
    index-name: orders
    index-type: order
refund:
  search:
    index-name: refunds
    index-type: refund
stock_send:
  search:
    index-name: stocks
    index-type: stock_send

rpc:
  mode: true
  dubbo:
    module: pousheng-index-consumer
    registry-address: ${POUSHENG_ZK_HOST:127.0.0.1}:${POUSHENG_ZK_PORT:2181}
    version: middle.1.0.0

redis:
  host: ${POUSHENG_REDIS_SESSION_HOST}
  port: ${POUSHENG_REDIS_SESSION_PORT}
  auth: ${POUSHENG_REDIS_SESSION_PASSWORD}
  max-total: 64
  max-idle: 8
  test-on-borrow: true

warehouse.shop.group.scan: ${WAREHOUSE_SHOP_GROUPS_SCAN_JOB_ENABLE:true}
warehouse.shop.group.scan.seconds: ${WAREHOUSE_SHOP_GROUPS_SCAN_SECONDS:30}