package com.pousheng.middle.order.service;

import com.pousheng.middle.order.model.PoushengEspLog;
import io.terminus.common.model.Response;

import java.util.Date;
import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: Esp快递日志读服务
 * Date: 2019-09-10
 */

public interface PoushengEspLogService {

    /**
     * 根据id查询Esp快递日志
     *
     * @param poushengEspLogId 主键id
     * @return Esp快递日志
     */
    Response<PoushengEspLog> findPoushengEspLogById(Long poushengEspLogId);

    /**
     * 创建PoushengEspLog
     *
     * @param poushengEspLog
     * @return 主键id
     */
    Response<Long> createPoushengEspLog(PoushengEspLog poushengEspLog);

    /**
     * 更新PoushengEspLog
     *
     * @param poushengEspLog
     * @return 是否成功
     */
    Response<Boolean> updatePoushengEspLog(PoushengEspLog poushengEspLog);

    /**
     * 根据主键id删除PoushengEspLog
     *
     * @param poushengEspLogId
     * @return 是否成功
     */
    Response<Boolean> deletePoushengEspLogById(Long poushengEspLogId);

    Response<PoushengEspLog> findPoushengEspLogByShipmentCode(String shipmentCode);

    Response<List<PoushengEspLog>> findLogToRetry(Integer synStatus, Integer retryNum, Date createdAtStart, Date createdAtEnd);
}
