package com.pousheng.middle.order.service;

import com.pousheng.middle.order.dto.reverseLogistic.ReverseExpressCriteria;
import com.pousheng.middle.order.dto.reverseLogistic.ReverseInstoreCriteria;
import com.pousheng.middle.order.model.ReverseExpressInfo;
import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;

/**
 * Code generated by terminus code gen
 * Desc: 读服务
 * Date: 2019-06-03
 */

public interface ReverseExpressInfoReadService {

    /**
     * 根据id查询
     * @param reverseExpressInfoId 主键id
     * @return 
     */
    Response<ReverseExpressInfo> findReverseExpressInfoById(Long reverseExpressInfoId);

    Response<ReverseExpressInfo> findReverseExpressInfoByExpressNo(String expressNo);

    Response<ReverseExpressInfo> findReverseExpressInfoByTransferOrderIdAndLineNo(String transferOrderId,String lineNo);


    Response<Paging<ReverseExpressInfo>> paging(ReverseExpressCriteria reverseExpressCriteria);

    Response<Long>  countReverseInstore(ReverseExpressCriteria reverseExpressCriteria);



}
