package com.pousheng.middle.order.service;

import com.pousheng.middle.order.model.ReverseExpressInfo;
import io.terminus.common.model.Response;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 写服务
 * Date: 2019-06-03
 */

public interface ReverseExpressInfoWriteService {

    /**
     * 创建ReverseExpressInfo
     * @param reverseExpressInfo
     * @return 主键id
     */
    Response<Long> createReverseExpressInfo(ReverseExpressInfo reverseExpressInfo);

    Response<Long> batchCreateOrUpdate(List<ReverseExpressInfo> reverseExpressInfoList);

    /**
     * 更新ReverseExpressInfo
     * @param reverseExpressInfo
     * @return 是否成功
     */
    Response<Boolean> updateReverseExpressInfo(ReverseExpressInfo reverseExpressInfo);

    /**
     * 根据主键id删除ReverseExpressInfo
     * @param reverseExpressInfoId
     * @return 是否成功
     */
    Response<Boolean> deleteReverseExpressInfoById(Long reverseExpressInfoId);


}