package com.pousheng.middle.order.service;

import com.pousheng.middle.order.model.ReverseHeadlessInfo;
import com.pousheng.middle.order.model.ReverseInstoreInfo;
import io.terminus.common.model.Response;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 写服务
 * Date: 2019-06-03
 */

public interface ReverseInstoreInfoWriteService {

    /**
     * 创建ReverseInstoreInfo
     * @param reverseInstoreInfo
     * @return 主键id
     */
    Response<Long> createReverseInstoreInfo(ReverseInstoreInfo reverseInstoreInfo);


    Response<Long> batchCreateOrUpdate(List<ReverseInstoreInfo> reverseInstoreInfoList);


    /**
     * 更新ReverseInstoreInfo
     * @param reverseInstoreInfo
     * @return 是否成功
     */
    Response<Boolean> updateReverseInstoreInfo(ReverseInstoreInfo reverseInstoreInfo);

    /**
     * 根据主键id删除ReverseInstoreInfo
     * @param reverseInstoreInfoId
     * @return 是否成功
     */
    Response<Boolean> deleteReverseInstoreInfoById(Long reverseInstoreInfoId);


}