package com.pousheng.middle.order.service;

import com.pousheng.middle.order.model.ReverseExpressInfo;
import com.pousheng.middle.order.model.ReverseHeadlessInfo;
import io.terminus.common.model.Response;

import java.util.List;

/**
 * Code generated by terminus code gen
 * Desc: 写服务
 * Date: 2019-06-03
 */

public interface ReverseHeadlessInfoWriteService {

    /**
     * 创建ReverseHeadlessInfo
     * @param reverseHeadlessInfo
     * @return 主键id
     */
    Response<Long> createReverseHeadlessInfo(ReverseHeadlessInfo reverseHeadlessInfo);

    Response<Long> batchCreateOrUpdate(List<ReverseHeadlessInfo> reverseHeadlessInfoList);


    /**
     * 更新ReverseHeadlessInfo
     * @param reverseHeadlessInfo
     * @return 是否成功
     */
    Response<Boolean> updateReverseHeadlessInfo(ReverseHeadlessInfo reverseHeadlessInfo);

    /**
     * 根据主键id删除ReverseHeadlessInfo
     * @param reverseHeadlessInfoId
     * @return 是否成功
     */
    Response<Boolean> deleteReverseHeadlessInfoById(Long reverseHeadlessInfoId);
}