package com.pousheng.middle.order.service;

import com.pousheng.middle.order.dto.reverseLogistic.ReverseInstoreCriteria;
import com.pousheng.middle.order.model.ReverseInstoreInfo;
import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;

import java.util.Map;

/**
 * Code generated by terminus code gen
 * Desc: 读服务
 * Date: 2019-06-03
 */

public interface ReverseInstoreInfoReadService {

    /**
     * 根据id查询
     * @param reverseInstoreInfoId 主键id
     * @return 
     */
    Response<ReverseInstoreInfo> findReverseInstoreInfoById(Long reverseInstoreInfoId);


    Response<ReverseInstoreInfo> findReverseExpressInfoByInstoreNoAndDetailNo(String instoreNo,String instoreDetailNo);


    Response<Paging<ReverseInstoreInfo>> paging(ReverseInstoreCriteria reverseInstoreCriteria);


    Response<Long>  countReverseInstore(ReverseInstoreCriteria reverseInstoreCriteria);

}
