package com.pousheng.middle.order.service;

import com.pousheng.middle.order.dto.reverseLogistic.ReverseHeadlessCriteria;
import com.pousheng.middle.order.model.ReverseHeadlessInfo;
import io.terminus.common.model.Paging;
import io.terminus.common.model.Response;

/**
 * Code generated by terminus code gen
 * Desc: 读服务
 * Date: 2019-06-03
 */

public interface ReverseHeadlessInfoReadService {

    /**
     * 根据id查询
     * @param reverseHeadlessInfoId 主键id
     * @return 
     */
    Response<ReverseHeadlessInfo> findReverseHeadlessInfoById(Long reverseHeadlessInfoId);


    Response<ReverseHeadlessInfo> findReverseHeadlessInfoByUniqueNo(String uniqueNo);

    Response<Paging<ReverseHeadlessInfo>> paging(ReverseHeadlessCriteria reverseHeadlessCriteria);

    Response<Long> countReverseHeadless(ReverseHeadlessCriteria reverseHeadlessCriteria);

}
