package com.pousheng.middle.order.dto.reverseLogistic;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen Desc: Model类 Date: 2019-06-03
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReverseExpressInfoDto extends  ReverseLogisticBase implements Serializable {
    private static final long serialVersionUID = 8526415038719338331L;

    /**
     * 交接单号
     */
    private String transferOrderId;

    /**
     * 行号
     */
    private String lineNo;

    /**
     * 是否有单 0-无 1-有
     */
    private Integer hasOrder;

    /**
     * 入库单号
     */
    private String instoreNo;


    private ReverseLogisticTime timeInfo;
    /**
     * 运单信息
     */
    private WaybillDto waybillDto;

    private String createdBy;

    private Date createdAt;


}
