logging:
  file: ${user.home}/logs/pousheng/erp.log
  level.*: INFO


server:
  context-path: /
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://${POUSHENG_MIDDLE_MYSQL_HOST}:${POUSHENG_MIDDLE_MYSQL_PORT}/${POUSHENG_MIDDLE_MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF8
    username: ${POUSHENG_MIDDLE_MYSQL_USERNAME}
    password: ${POUSHENG_MIDDLE_MYSQL_PASSWORD}

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: >
        com.pousheng.(erp|auth).model,
        com.pousheng.middle.warehouse.model,
        com.pousheng.middle.order.model,
        io.terminus.parana.(item|category|brand|spu|shop).model,
        io.terminus.parana.(order|cart|express|promotion|delivery|settle).model,
        io.terminus.open.client.common.(mappings|token|shop).model,
        io.terminus.open.client.item.model



redis:
  host: ${POUSHENG_REDIS_HOST}
  port: ${POUSHENG_REDIS_PORT}
  auth: ${POUSHENG_REDIS_PASSWORD}
  max-total: 10
  max-idle: 2
  test-on-borrow: true


rpc.mode: false
rpc.dubbo:
  module: pousheng-middle
  registryAddress: ${POUSHENG_ZK_HOST}:${POUSHENG_ZK_PORT}

gateway:
  erp:
    host: http://localhost:27073
    accessKey: 58281fefa2dfe674e64a840c5f087a6e3b538a1f
  member:
    host: http://api-test-member.pousheng.com

open.api.app.key: ${OPEN_API_APP_KEY}
open.api.secret: ${OPEN_API_SECRET}
open.api.gateway: ${OPEN_API_GATEWAY}



user.center.gateway: ${USER_CENTER_GATEWAY}