logging:
  file: ${user.home}/logs/pousheng/erp.log
  level.*: INFO


server:
  context-path: /
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://${POUSHENG_MIDDLE_MYSQL_HOST}:${POUSHENG_MIDDLE_MYSQL_PORT}/${POUSHENG_MIDDLE_MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF8
    username: ${POUSHENG_MIDDLE_MYSQL_USERNAME}
    password: ${POUSHENG_MIDDLE_MYSQL_PASSWORD}

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: >
        com.pousheng.erp.model,
        com.pousheng.middle.warehouse.model,
        io.terminus.parana.(item|category|brand|spu|shop).model,
        io.terminus.parana.(order|cart|express|promotion|delivery|settle).model,
        io.terminus.open.client.common.(mappings|token|shop).model,
        io.terminus.open.client.item.model



redis:
  host: ${POUSHENG_REDIS_HOST}
  port: ${POUSHENG_REDIS_PORT}
  auth: ${POUSHENG_REDIS_PASSWORD}
  max-total: 10
  max-idle: 2
  test-on-borrow: true


rpc.mode: true
rpc.dubbo:
  module: pousheng-middle
  registryAddress: 127.0.0.1:2181