logging:
  file: ${user.home}/logs/pousheng/erp.log
  level.*: INFO


server:
  context-path: /
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://${POUSHENG_MIDDLE_MYSQL_HOST}:${POUSHENG_MIDDLE_MYSQL_PORT}/${POUSHENG_MIDDLE_MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF8
    username: ${POUSHENG_MIDDLE_MYSQL_USERNAME}
    password: ${POUSHENG_MIDDLE_MYSQL_PASSWORD}

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: >
        com.pousheng.(erp|auth).model,
        com.pousheng.middle.warehouse.model,
        com.pousheng.middle.order.model,
        io.terminus.parana.(item|category|brand|spu|shop).model,
        io.terminus.parana.(order|cart|express|promotion|delivery|settle|auth).model,
        io.terminus.open.client.common.(mappings|token|shop).model,
        io.terminus.open.client.item.model




session:
  cookie-context-path: /
  cookie-domain: pousheng.com
  cookie-name: msid
  cookie-max-age: 1800
  source: redis
  serialize-type: json
  redis-host: ${POUSHENG_REDIS_HOST}
  redis-port: ${POUSHENG_REDIS_PORT}
  redis-auth: ${POUSHENG_REDIS_PASSWORD}
  redis-index: 0
  redis-cluster: false
  redis-test-on-borrow: true
  redis-max-total: 10
  redis-max-idle: 0
  redis-prefix: afsession

redis:
  host: ${POUSHENG_REDIS_HOST}
  port: ${POUSHENG_REDIS_PORT}
  auth: ${POUSHENG_REDIS_PASSWORD}
  max-total: 10
  max-idle: 2
  test-on-borrow: true


rpc.mode: false
rpc.dubbo:
  module: pousheng-middle
  registryAddress: ${POUSHENG_ZK_HOST}:${POUSHENG_ZK_PORT}

gateway:
  erp:
    host: http://esbt.pousheng.com
    accessKey: 58281fefa2dfe674e64a840c5f087a6e3b538a1f
  member:
    host: http://api-test-member.pousheng.com
  uc:
    host: ${USER_CENTER_GATEWAY}
  hk:
    host: http://esbt.pousheng.com

open.api.app.key: ${OPEN_API_APP_KEY}
open.api.secret: ${OPEN_API_SECRET}
open.api.gateway: ${OPEN_API_GATEWAY}


azure:
  oss:
    defaultEndpointsProtocol: https
    accountName: devdiag685
    accountKey: ibH/7kzCiXTXAN+tEI4TGKc8xwpXQtGYTb3b3Pv1xE0SVct5apwwKbKCwybSWnY1Grp8ioh8N1VGjhlzvvf/dA==
    endpointSuffix: core.chinacloudapi.cn