insert into `pousheng_sku_group_rules` (card_id, kind_id, rule_type, split_char, last_start, created_at, updated_at)
values ('NIKE(耐克)',null,2, null,3, now(), now()),
       ('SKECHERS(斯凯奇)',null,1, '/',null,now(),now() ),
       ('CONVERSE(匡威)','服装',3,'-',3,now(),now()),
       ('UNDER ARMOUR',null,2, null,3, now(), now()),
       ('THE NORTH FACE(乐斯菲斯)',null,2, null,4, now(), now()),
       ('LACOSTE(鳄鱼)',null, 2, null,3, now(),now()),
       ('ASICS(爱世克斯)',null, 1,'-',null,now(),now()),
       ('ONITSUKA TIGER(鬼冢虎)',null, 1,'-',null,now(),now()),
       ('DIADORA(迪阿多纳)',null,2, null,5, now(),now()),
       ('PONY(波尼)',null,2, null,2, now(),now()),
       ('SKECHERS(斯凯奇)',null,1, '-',null,now(),now()),
       ('KIPLING',null,2, null,3, now(),now()),
       ('GEOX(健乐士)',null,2, null,4, now(),now()),
        ('ABLE JEANS',null,2, null,3, now(),now()),
        ('JACKWOLFSKIN(狼爪)',null,2, null,3, now(),now()),
        ('COLUMBIA(哥伦比亚)',null,2, null,3, now(),now()),
        ('MIZUNO(美津浓)','鞋子',2, null,3, now(),now()),
        ('ODLO(奥递尔)',null, 1,'-',null,now(),now()),
        ('OAKLEY(欧克利)',null, 1,'-',null,now(),now()),
        ('SOFSOLE(舒足)',null,2, null,3, now(),now()),
        ('BMAI(必迈)',null, 1,'-',null,now(),now()),
        ('YY',null,2, null,2, now(),now()),
        ('YY KIDS',null,2, null,2, now(),now());