package com.pousheng.middle.order.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: 配置表Model类
 * Date: 2019-06-26
 */
@Data
public class PoushengConfig implements Serializable {
    //TODO: Do not forget add "serialVersionUID" field AND change package path!

    private Long id;

    private String type;

    private String content;

    private Date createdAt;

    private Date updatedAt;
}
