package com.pousheng.middle.order.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Code generated by terminus code gen
 * Desc: Esp快递日志Model类
 * Date: 2019-09-17
 */
@Data
public class PoushengEspLog implements Serializable {
    //TODO: Do not forget add "serialVersionUID" field AND change package path!

    private Long id;

    /**
     * 接口类型
     */
    private String type;

    /**
     * 类型名称
     */
    private String typeName;

    /**
     * 请求时间
     */
    private Date requestTime;

    /**
     * 请求体
     */
    private String requestContent;

    /**
     * 返回体
     */
    private String responseContent;

    /**
     * 门店编码
     */
    private String stroeCode;

    /**
     * 门店名称
     */
    private String stroeName;

    /**
     * 快递代码
     */
    private String expressCompanyCode;

    /**
     * 快递单号
     */
    private String expressNo;

    /**
     * 原始平台单号
     */
    private String originalOrderNo;

    /**
     * mpos单号
     */
    private String mposOrderNo;

    /**
     * 中台发货单号
     */
    private String middleShipmentNo;

    private Integer retryNum = 1;

    /**
     * 同步状态，1同步成功,-1同步失败
     */
    private Integer synStatus;

    private Date createdAt;

    private Date updatedAt;

    /**
     * 发货单创建时间
     */
    private Date shipmentCreatedAt;

    /**
     * 发货单更新时间
     */
    private Date shipmentUpdatedAt;
}
